library(geojsonio)
library(plyr)
library(dplyr)
library(ggplot2) # 3.4.3
library(sp)
library(broom)
library(sf)
library(rnaturalearth)
library(maps)
library(rmapshaper)
library(raster)
library(see)
library(eurostat)
library(stringr)
library(data.table)
library(str2str)
library(exactextractr)
library(terra)

